### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 2: ordinal not in range(128)

### ISSUE THREAD

**Issue by minji-o-j** [minji-o-j/YOLOv2#16]
Called with args:
Namespace(batch_size=2, conf_thresh=0.005, dataset='voc07test', model_name='yolov2_epoch_160', nms_thresh=0.45, num_workers=1, output_dir='output', use_cuda=True, vis=False)
Traceback (most recent call last):
  File "test.py", line 164, in <module>
    test()
  File "test.py", line 93, in test
    val_dataset = RoiDataset(val_imdb, train=False)
  File "/home/minji/pt2/yolov2.pytorch/dataset/roidb.py", line 20, in __init__
    self._roidb = imdb.roidb
  File "/home/minji/pt2/yolov2.pytorch/dataset/imdb.py", line 56, in roidb
    self._roidb = self.roidb_handler()
  File "/home/minji/pt2/yolov2.pytorch/dataset/pascal_voc.py", line 104, in gt_roidb
    roidb = pickle.load(fid)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 2: ordinal not in range(128)
2.1930184364318848

**Comment by minji-o-j** [comment]
윈도우에선 안바꿔도돌아갔는데 리눅스에선 바꿔줘야함 😭😭😭😭😭😭😭😭😭😭😭
