### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by minji-o-j** [minji-o-j/YOLOv2#42]
```
call with args: Namespace(export_video_frame=False, model_name='yolov2_epoch_160', output_dir='output', save_video_name='l4d2', use_cuda=True, video_path='images/left_4_dead_2.mp4')
loading model from output/yolov2_epoch_160.pth
model loaded
1 : im detect, cost time 0.021208, FPS: 47
Traceback (most recent call last):
  File "video_saveframe.py", line 252, in <module>
    demo()
  File "video_saveframe.py", line 153, in demo
    print(tuple(np.round(det_boxes[i, :4]).astype(np.int64)))
IndexError: too many indices for array
```

**Comment by minji-o-j** [comment]
```py
bbox=tuple(np.round(det_boxes[i, :4]).astype(np.int64)
print(bbox[0]) #과 같이 접근
```
