### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by minji-o-j** [minji-o-j/YOLOv2#43]
```
(base) C:\Users\user>pip3 install labelImg
Collecting labelImg
  Using cached labelImg-1.8.4.tar.gz (242 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-zkai36d5\\labelimg\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-zkai36d5\\labelimg\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-lyxuyme4'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-zkai36d5\labelimg\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-zkai36d5\labelimg\setup.py", line 20, in <module>
        readme = readme_file.read()
    UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 7520: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

labelImg 설치시 오류

**Comment by minji-o-j** [comment]
```py
pip install mysql-connector-python
```

**Comment by minji-o-j** [comment]
그냥 pip install labelImg말고 
#44 처럼
