### ISSUE TITLE
RuntimeError: grad can be implicitly created only for scalar outputs

### ISSUE THREAD

**Issue by minji-o-j** [minji-o-j/YOLOv2#47]
Traceback (most recent call last):
  File "train_newmodel.py", line 283, in <module>
    train()
  File "train_newmodel.py", line 222, in train
    loss.backward()
  File "/home/minji/.local/lib/python3.6/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/minji/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 121, in backward
    grad_tensors = _make_grads(tensors, grad_tensors)
  File "/home/minji/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 47, in _make_grads
    raise RuntimeError("grad can be implicitly created only for scalar outputs")
RuntimeError: grad can be implicitly created only for scalar outputs

**Comment by minji-o-j** [comment]
텐서에 숫자 이외에 문자열 존재
